# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS frontend
WORKDIR /build
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --no-audit --no-fund
COPY frontend/ ./
ENV VITE_OUT_DIR=/build/dist
RUN npm run build


FROM python:3.12-slim AS backend

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# Calibre is baked in for MOBI/AZW conversion + fetch-ebook-metadata enrichment.
# CBR support (Phase 2) will need an unrar-compatible tool — `unrar` moved to
# Debian non-free in trixie, so we'll add `unar` or `unrar-free` when that
# phase lands. For Phase 1 (EPUB only) neither is required.
RUN apt-get update && apt-get install -y --no-install-recommends \
        calibre \
        libmagic1 \
        libxml2 \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip first — the base image's pip 25.0.1 has known CVEs (malicious-wheel
# RCE, unsafe archive/symlink extraction, path traversal). pip only bootstraps uv.
# Also drop the stale pip wheel bundled in ensurepip (uv never uses it) so Trivy
# has no 25.0.1 left to flag.
RUN python -m pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir uv \
    && find /usr/local/lib -path '*/ensurepip/_bundled/*' -name 'pip-*.whl' -delete

WORKDIR /app
COPY pyproject.toml ./
# uv.lock is generated by `uv sync` locally; copy if present.
COPY uv.lock* ./

RUN uv sync --no-dev --extra formats

COPY src/ ./src/
COPY alembic/ ./alembic/
COPY alembic.ini ./

COPY --from=frontend /build/dist/ ./src/despereaux/static/reader/

ENV PYTHONPATH=/app/src \
    PATH="/app/.venv/bin:$PATH" \
    DESPEREAUX_PROJECT_ROOT=/app

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD curl -fsS http://127.0.0.1:8000/healthz || exit 1

# Single worker: this is an async I/O-bound app and the lifespan owns singleton
# state (scanner, watcher, background tasks). Multiple workers each run the lifespan,
# duplicating migrations / scans / watchers and causing SQLAlchemy identity-map
# races during concurrent ingest. Front with nginx for true parallelism if ever needed.
CMD ["uvicorn", "despereaux.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
