# syntax=docker/dockerfile:1.7

FROM node:22-alpine AS frontend
WORKDIR /build
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --no-audit --no-fund
COPY frontend/ ./
ENV VITE_OUT_DIR=/build/dist
RUN npm run build


FROM python:3.12-slim AS backend

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# Calibre is baked in for MOBI/AZW conversion + fetch-ebook-metadata enrichment.
# unrar is needed by the rarfile python package for CBR support.
RUN apt-get update && apt-get install -y --no-install-recommends \
        calibre \
        unrar \
        libmagic1 \
        libxml2 \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

WORKDIR /app
COPY pyproject.toml ./
# uv.lock is generated by `uv sync` locally; copy if present.
COPY uv.lock* ./

RUN uv sync --no-dev --extra formats

COPY src/ ./src/
COPY alembic/ ./alembic/
COPY alembic.ini ./

COPY --from=frontend /build/dist/ ./src/despereaux/static/reader/

ENV PYTHONPATH=/app/src \
    PATH="/app/.venv/bin:$PATH" \
    DESPEREAUX_PROJECT_ROOT=/app

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD curl -fsS http://127.0.0.1:8000/healthz || exit 1

CMD ["uvicorn", "despereaux.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
